project:
  type: website

website:
  title: "MLR Workshop"
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: "Home"
      - href: slide_container.qmd
        text: "Slides"
      - href: datasets.qmd
        text: "Datasets"
      - icon: github
        href: https://www.github.com/jmgirard/tips2022ml
  search: false
  page-footer: "Copyright 2022 © Jeffrey Girard"

format:
  html:
    theme: cosmo
    css: styles.css
